version: '3'

services:
  app:
    container_name: app
    build: ./app
    ports:
      - "5000:5000"
    networks:
      - appnet

  nginx:
    container_name: nginx
    image: nginx:alpine-slim
    ports:
    - 80:80
    volumes:
      #- "./proxy/conf:/etc/nginx/conf.d"
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
     
    depends_on:
      - app
    networks:
      - appnet


networks:
  appnet:
