FROM python:3.11

COPY requirements.txt .
RUN pip install -r requirements.txt

WORKDIR /app
COPY templates ./templates
COPY static/01.jpg static/02.jpg static/03.jpeg static/04.jpg static/05.jpg static/06.jpg static/funcs.py static/logo.png ./static/
COPY *.json ./static/
COPY app.py .




ENV PYTHONUNBUFFERED=1

USER root
EXPOSE 5000

CMD ["bash", "-c", "python /app/static/funcs.py & python app.py"]
