FROM python:3.11

WORKDIR /app
COPY templates ./templates
COPY static/01.jpg static/02.jpg static/03.jpeg static/funcs.py static/logo.png ./static/
COPY *.json ./static/
COPY app.py .
COPY requirements.txt .

RUN pip install -r requirements.txt

USER root
EXPOSE 5000

CMD ["bash", "-c", "python /app/static/funcs.py & python app.py"]
